### ISSUE TITLE
FC Layer

### ISSUE THREAD

**Issue by ahmdtaha** [allenai/hidden-networks#5]
Hi,

I noticed that code does not support fully connected layers (nn. Linear). The code seems to use [conv1x1 instead](https://github.com/allenai/hidden-networks/blob/dddf2d093de568fc76d460a77fa2650e56e79c1a/models/frankle.py#L22).

Is there a technical reason that prevents a SubnetLinear? like [SubnetConv](https://github.com/allenai/hidden-networks/blob/dddf2d093de568fc76d460a77fa2650e56e79c1a/utils/conv_type.py#L36)

Thanks

**Comment by mitchellnw** [comment]
Nope, just trying to write as little code as possible!
