### ISSUE TITLE
Paper results on CIFAR-10

### ISSUE THREAD

**Issue by ofirzaf** [allenai/hidden-networks#7]
Hi,
I want to reproduce the paper's results on CIFAR-10 dataset and I saw in the paper that you experimented with VGG like networks and I can't seem to find a reference to the networks you used in this repo.

Can you please post official results you got on CIFAR-10 with the VGG like models you used or with resnets for cifar?
Alternatively, can you tell me what arguments I need to use to reproduce the results using your repo?

Thanks

**Comment by mitchellnw** [comment]
Sorry for the delay -- all of the configurations for the experiments in the paper are in `configs`. The `smallscale` folder is the configs for the CIFAR experiments. Experiments can be run with

```
python main.py --config configs/smallscale/conv4/conv4_usc_unsigned.yml \
               --multigpu 0 \
               --name example \
               --data <path/to/data-dir> \
               --prune-rate 0.5
```

and there is some more info on this in the README. Also all those VGG-like networks are [here](https://github.com/allenai/hidden-networks/blob/master/models/frankle.py) -- the naming is the same as in the paper.

Thanks for the question,
Mitchell
